config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'comments/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ####devise###
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }

  ###enduser###
  #homes controller
  root to: 'home#top'
  get '/about', to: 'home#about', as: 'about'
  #users controller
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
  patch '/users/:id', to: 'users#retire', as: 'retire'
  get '/users/retire/complete', to: 'users#complete', as: 'retire_complete'
  #rooms controller
  get '/users/:id/rooms', to: 'rooms#index', as:'myrooms'
  resources :rooms, only: [:create,:show]
  resources :users do
    post '/rooms' => 'rooms#create'
  end

  mount ActionCable.server => '/cable'
  #messages controller
  resources :messages, only: [:create]
  #rounds controller
  get '/myrounds', to: 'rounds#myrounds'
  get '/history', to: 'rounds#history'
  get '/search/rounds', to: 'rounds#search'
  get '/sort/rounds', to: 'rounds#sort'
  post '/round/:id', to: 'rounds#apply', as: 'apply_round'
  patch '/round/:id', to: 'rounds#approval', as: 'approval_round'
  delete '/round/:id', to: 'rounds#refuse', as: 'refuse_round'
  resources :rounds
  get '/maprequest', to: 'rounds#map', as: 'map_request'
  #comments controller
  post '/rounds/:id/comments', to: 'comments#create', as: 'comments'
  get '/rounds/:id/comments/new', to: 'comments#new', as: 'new_comment'
  delete '/comments/:id', to: 'comments#destroy', as: 'comment'

  ###admin###
  namespace :admins do
  	#admins/clients controller
  	resources :clients,  only: [:index]
  	#admins/rounds controller
  	resources :rounds,  only: [:index]
  end

end

app/models/round.rb
class Round < ApplicationRecord

  has_many :users, through: :comments
  has_many :comments, dependent: :destroy
  has_many :users, through: :users_rounds
  has_many :users_rounds, dependent: :destroy
  belongs_to :prefecture
  belongs_to :map
  accepts_nested_attributes_for :map

  validates :round_title, presence: true, length: { minimum: 5, maximum: 30 }
  validates :round_date, presence: true
  validates :round_intro, presence: true
  validates :recruitment_sex, presence: true
  validates :capacity, presence: true
end

app/controllers/admins/rounds_controller.rb
class Admins::RoundsController < ApplicationController
  def index
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search, :sort, :show]
  before_action :correct_round, only: [:edit, :update, :destroy, :approval, :refuse]

  def myrounds
    @member_rounds = UsersRound.joins(:round).where(user_id: current_user.id, approval_flag: "1").order("rounds.round_date ASC")
    @apply_rounds = UsersRound.joins(:round).where(user_id: current_user.id, approval_flag: "0").order("rounds.round_date ASC")
  end

  def history
    @joined_rounds = UsersRound.joins(:round).where(user_id: current_user.id, approval_flag: "1").order("rounds.round_date DESC")
  end

  def index
    @rounds = Round.where("round_date > ?", Date.current).order("round_date ASC").page(params[:page]).per(10)
    @regions = Region.all
  end

  def search
    if params[:region_id] == '9'
      r_d = params[:round_date] + '-01'
      r_d = r_d.to_date
      @rounds = Round.where(round_date: r_d.beginning_of_month..r_d.end_of_month)
      @rounds = Kaminari.paginate_array(@rounds).page(params[:page]).per(10)
      @regions = Region.all
    else
      @rounds = Round.joins(prefecture: :region).select("rounds.*").where("region_id LIKE ? AND round_date LIKE ?","%#{params[:region_id]}%","%#{params[:round_date]}%")
      @rounds = Kaminari.paginate_array(@rounds).page(params[:page]).per(10)
      @regions = Region.all
    end
    render :index
  end

  def sort
    if params[:sort_type] == "1"
      @rounds = Round.where("round_date > ?", Date.current).order('round_date ASC').page(params[:page]).per(10)
      @regions = Region.all
      render :index
    elsif params[:sort_type] == "2"
      @rounds = Round.where("round_date > ?", Date.current).order('id ASC').page(params[:page]).per(10)
      @regions = Region.all
      render :index
    end
  end

  def show
    @round = Round.find(params[:id])
    @master = @round.users_rounds.first
    if user_signed_in?
      @user_round = UsersRound.where(user_id: current_user.id).where(round_id: @round.id)
      @member = UsersRound.where(user_id: current_user.id).where(round_id: @round.id).where(approval_flag: "1")
    end
    @comment = Comment.new
    @comments = Comment.where(round_id: @round.id).order('id DESC')
    @members = UsersRound.where(round_id: @round.id).where(approval_flag: "1")
    @apply = UsersRound.where(round_id: @round.id).where(approval_flag: "0")

    @lat = @round.map.latitude
    @lng = @round.map.longitude
    @place = @round.map.place
  end

  def new
    @round = Round.new
    @round.build_map
    @prefecture = Prefecture.all
  end

  def map
  end

  def create
    @round = Round.new(round_params)
    @map = Map.find_by(place: params[:round][:map_attributes][:place])
    if @map
      @round.map_id = @map.id
    else
     @round.build_map(place: params[:round][:map_attributes][:place])
    end
    @round.users_rounds.build([{user_id: current_user.id, approval_flag: 1}])
    if  @round.save
      redirect_to round_path(@round)
    else
      @prefecture = Prefecture.all
      render :new
    end
  end

  def edit
    @round = Round.find(params[:id])
    @prefecture = Prefecture.all
    @map = Map.all
  end

  def update #ラウンド情報編集
    @round = Round.find(params[:id])
    @map = Map.find_by(place: params[:round][:map_attributes][:place])
    if @map
      @round.map_id = @map.id
    else
      @round.build_map(place: params[:round][:map_attributes][:place])
    end
    if @round.update(round_params)
      redirect_to round_path(@round)
    else
      @prefecture = Prefecture.all
      render :edit
    end
  end

  def destroy #ラウンド削除
    @round = find(params[:id])
    @round.destroy
    redirect_to rounds_path
  end

  def apply #参加申請
    @round = Round.find(params[:id])
    @round.users_rounds.create([{user_id: current_user.id, round_id: @round.id, approval_flag: 0}])
    redirect_to round_path(@round)
  end

  def approval #参加承認
    @round = Round.find(params[:round_id])
    @users_round = UsersRound.find_by(user_id: params[:user_id], round_id: @round.id)
    @users_round.update(approval_flag: 1)
    redirect_to round_path(@round)
  end

  def refuse #参加拒否
    @round = Round.find(params[:round_id])
    @users_round = UsersRound.find_by(user_id: params[:user_id], round_id: @round.id)
    @users_round.destroy
    redirect_to round_path(@round)
  end

  private

  def round_params
    params.require(:round).permit(
                                  :map_id,
                                  :prefecture_id,
                                  :round_title,
                                  :round_date,
                                  :round_intro,
                                  :recruitment_sex,
                                  :capacity,
                                  map_attribute:[:id, :place]
                                  )
  end

  def users_round_params
    params.require(:users_round).permit(:user_id, :round_id, :approval_flag)
  end

  def correct_round
    round = Round.find(params[:id])
    master = round.users_rounds.first
    if current_user != master.user
      redirect_to round_path(round)
    end
  end

end

app/helpers/admins/rounds_helper.rb
module Admins::RoundsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_comment.html.erb
  <tr class="active">
    <th>
      <span>
        投稿者 ：<%= link_to c.user.user_name, user_path(c.user_id) %>
      </span>
      <span>
        <%= c.created_at.strftime("20%y/%m/%d %H:%M") %>
      </span>
      <% if user_signed_in? %>
        <% if c.user_id == current_user.id %>
          <sapn>
            <%= link_to "削除", comment_path(c.id), method: :delete, class:"btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
          </span>
        <% end %>
      <% end %>
    </th>
  </tr>
  <tr>
    <td>
      <%= simple_format(c.comment) %>
    </td>
  </tr>

app/views/rounds/edit.html.erb
<h3 class="heading">主催ラウンド編集</h3>

<%= form_for(@round) do |f| %>

  <div class="field">
    <%= f.label :"日程" %><br />
    <%= f.date_field :round_date, selected: Date.today %>
  </div>

  <div class="field">
    <%= f.label :"開催都道府県" %><br />
        <%= f.collection_select(:prefecture_id, @prefecture, :id, :pref_name, {prompt: "選択してください"}) %>
  </div>

  <div class="field">
    <%= f.label :"募集性別" %><br />
    <%= f.select :recruitment_sex, [["どちらでも",2],["男性",0],["女性",1]], prompt: "選択してください" %>
  </div>

  <div class="field">
    <%= f.label :"定員" %><br />
    <%= f.number_field :capacity, min: 2, max: 100 %>
  </div>

  <%= f.fields_for :map do |m| %>
    <div class="field">
      <%= m.label :"コース" %><br />
      <%= m.text_field :place, size: 50, autofocus: true, id:"place-search", placeholder:"ゴルフ場名を入力"  %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"タイトル" %><br />
    <%= f.text_field :round_title, size: 50,autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :"詳細" %><br />
    <%= f.text_area :round_intro, size: "80x10"  %>
  </div>

   <div class="actions">
    <%= f.submit "更新", class:"btn btn-primary" %>
  </div>

  <div>
    <%= link_to "ラウンド削除", round_path(@round), method: :delete, class:"btn btn-danger", "data-confirm" => "本当に削除しますか？この操作は取り消せません。" %>
  </div>
<% end %>

<script>
function initMap() {

  var input = /** @type {!HTMLInputElement} */(
    document.getElementById('place-search'));
  hoge = new google.maps.places.Autocomplete(input, {
    componentRestrictions: {country: 'jp'},
    types: ['establishment'],
  });
  hoge.addListener('place_changed', function() {
    input.value = this.getPlace().name;
  });

}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&libraries=places&callback=initMap"
            async defer></script>

app/views/rounds/history.html.erb
<h3 class="my-heading">ラウンド履歴</h3>
<!--ラウンド一覧情報-->
<div class="round-index">

  <% @joined_rounds.each do |jr| %>
    <% if Date.current > jr.round.round_date %>
      <div class="row round-index-box">
        <div class="left-box col-sm-3 col-xs-3">
          <div>
            <%= jr.round.round_date.strftime("20%y年%m月%d日") %>
          </div>
          <div>
            <%= "場　所：" + jr.round.prefecture.pref_name %>
            <!-- 地方id(非表示) -->
            <% jr.round.prefecture.region_id %>
          </div>
          <div>
            <%= "参加数：" + jr.round.users_rounds.where(approval_flag: "1").count.to_s %>
          </div>
          <div>
            <%= "定　員：" + jr.round.capacity.to_s %>
          </div>
        </div>
        <div class="right-box col-sm-9 col-xs-9">
          <div>
            <%= link_to jr.round.round_title, round_path(jr.round) %>
          </div>
          <div>
            <%= "コース名：" + jr.round.map.place %>
          </div>
          <div>
            <%= "主催者　：" + jr.round.users_rounds.first.user.user_name %>
          </div>
          <div>
            <%= "内　容　：" + jr.round.round_intro.truncate(50, omission: '...') %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/rounds/index.html.erb
<h3 class="heading">ラウンド募集一覧</h3>

<% if user_signed_in? %>
  <div>
    <%= link_to "主催ラウンドを作成", new_round_path, class:"btn btn-info" %>
  <div>
<% end %>
<!--検索・ソート-->
<div class="round-search">
  <div>絞り込み検索</div>
  <%= form_tag({controller: "rounds", action: "search" }, {method: "get"}) do %>
    <%= select_tag(:region_id, options_from_collection_for_select(@regions, :id, :region_name, params[:region_id])) %>
    <%= select_tag(:round_date, options_for_select([["#{Date.current.strftime("%m月")}", "#{Date.current.strftime("20%y-%m")}"],
                                                    ["#{Date.current.next_month(1).strftime("%m月")}", "#{Date.current.next_month(1).strftime("20%y-%m")}"],
                                                    ["#{Date.current.next_month(2).strftime("%m月")}", "#{Date.current.next_month(2).strftime("20%y-%m")}"]
                                                    ], :selected => params[:round_date])) %>
    <%= submit_tag "検索" %>
  <% end %>

<!--   <div>並び替え</div>
    link_to "開催日順", sort_rounds_path(sort_type: '1')
    link_to "　新着順", sort_rounds_path(sort_type: '2')
 --></div>

<!--ラウンド一覧情報-->
<div class="round-index">

  <div class="pagenate">
    <%= paginate @rounds %>
  </div>

  <% @rounds.each do |round| %>
    <div class="row round-index-box">
      <div class="left-box col-sm-3 col-xs-3">
        <div>
          <!-- 日程 -->
          <%= round.round_date.strftime("20%y年%m月%d日") %>
        </div>
        <div>
          <%= "場　所：" + round.prefecture.pref_name %>
          <!-- 地方id(非表示) -->
          <% round.prefecture.region_id %>
        </div>
        <div>
          <%= "参加数：" + round.users_rounds.where(approval_flag: "1").count.to_s %>
        </div>
        <div>
          <%= "定　員：" + round.capacity.to_s %>
        </div>
      </div>
      <div class="right-box col-sm-9 col-xs-9">
        <div>
          <%= link_to round.round_title, round_path(round) %>
        </div>
        <div>
          <%= "コース名：" + round.map.place %>
        </div>
        <div>
          <%= "主催者　：" + round.users_rounds.first.user.user_name %>
        </div>
        <div class="index-intro-title">
          内　容：
        </div>
        <div class="index-intro-text">
          <%= round.round_intro.truncate(50, omission: '...') %>
        </div>
      </div>
    </div>
  <% end %>
  <!-- end  -->

  <div class="pagenate">
    <%= paginate @rounds %>
  </div>

</div>

app/views/rounds/map.js.erb
// (function(){
//   // 位置情報をもつ変数を用意
//   let pos = new google.maps.LatLng(
//    <%= @la[0] %>, //latitude
//    <%= @latlng[1] %>  //longitude
//   );

//   mapInstance.setCenter(pos)
//   let marker = new google.maps.Marker({
//     map: mapInstance,
//     position: pos
//   });
// })()

app/views/rounds/myrounds.html.erb
<h3 class="my-heading">ラウンド予定一覧</h3>


<h4 class="myround-heading">主催ラウンド</h4>
<div>
  <%= link_to "主催ラウンドを作成", new_round_path, class:"btn btn-info" %>
</div>
<% @member_rounds.each do |master| %>
  <% if master.round.users_rounds.first.user_id == current_user.id %>
    <% if Date.current < master.round.round_date %>
      <div class="row round-index-box">
        <div class="left-box col-sm-3 col-xs-3">
          <div>
            <%= master.round.round_date.strftime("20%y年%m月%d日") %>
          </div>
          <div>
            <%= "場　所：" + master.round.prefecture.pref_name %>
          </div>
          <div>
            <%= "参加数：" + master.round.users_rounds.where(approval_flag: "1").count.to_s %>
          </div>
          <div>
            <%= "定　員：" + master.round.capacity.to_s %>
          </div>
        </div>
        <div class="right-box col-sm-9 col-xs-9">
          <div>
            <%= link_to master.round.round_title, round_path(master.round_id) %>
          </div>
          <div>
            <%= "コース名：" + master.round.map.place %>
          </div>
          <div>
            <%= "主催者　：" + master.round.users_rounds.first.user.user_name %>
          </div>
          <div class="col-sm-2">
            内　容：
          </div>
          <div class="col-sm-10">
            <%= master.round.round_intro.truncate(50, omission: '...') %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

<h4 class="myround-heading">参加ラウンド</h4>
<% @member_rounds.each do |member| %>
  <% unless member.round.users_rounds.first.user_id == current_user.id %>
    <% if Date.current < member.round.round_date %>
      <div class="row round-index-box">
        <div class="left-box col-sm-3 col-xs-3">
          <div>
            <%= member.round.round_date.strftime("20%y年%m月%d日") %>
          </div>
          <div>
            <%= "場　所：" + member.round.prefecture.pref_name %>
          </div>
          <div>
            <%= "参加数：" + member.round.users_rounds.count.to_s %>
          </div>
          <div>
            <%= "定　員：" + member.round.capacity.to_s %>
          </div>
        </div>
        <div class="right-box col-sm-9 col-xs-9">
          <div>
            <%= link_to member.round.round_title, round_path(member.round_id) %>
          </div>
          <div>
            <%= "コース名：" + member.round.map.place %>
          </div>
          <div>
            主催者　：<%= link_to member.round.users_rounds.first.user.user_name, user_path(member.round.users_rounds.first.user_id) %>
          </div>
          <div>
            <%= "内　容　：" + member.round.round_intro.truncate(50, omission: '...') %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

<h4 class="myround-heading">参加申請中</h4>
<% @apply_rounds.each do |apply| %>
  <% if Date.current < apply.round.round_date %>
    <div class="row round-index-box">
      <div class="left-box col-sm-3 col-xs-3">
        <div>
          <%= apply.round.round_date.strftime("20%y年%m月%d日") %>
        </div>
        <div>
          <%= "場　所：" + apply.round.prefecture.pref_name %>
        </div>
        <div>
          <%= "参加数：" + apply.round.users_rounds.count.to_s %>
        </div>
        <div>
          <%= "定　員：" + apply.round.capacity.to_s %>
        </div>
      </div>
      <div class="right-box col-sm-9 col-xs-9">
        <div>
          <%= link_to apply.round.round_title, round_path(apply.round_id) %>
        </div>
        <div>
          <%= "コース名：" + apply.round.map.place %>
        </div>
        <div>
          主催者　：<%= link_to apply.round.users_rounds.first.user.user_name, user_path(apply.round.users_rounds.first.user_id) %>
        </div>
        <div>
          <%= "内　容　：" + apply.round.round_intro.truncate(50, omission: '...') %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/rounds/new.html.erb
<h3 class="heading">主催ラウンド作成</h3>

<%= form_for(@round) do |f| %>

  <div class="field">
    <%= f.label :"日程" %><br />
    <%= f.date_field :round_date, selected: Date.today %>
  </div>

  <div class="field">
    <%= f.label :"開催都道府県" %><br />
    <%= f.collection_select(:prefecture_id, @prefecture, :id, :pref_name, {prompt: "選択してください"}) %>
  </div>

  <div class="field">
    <%= f.label :"募集性別" %><br />
    <%= f.select :recruitment_sex, [["どちらでも",2],["男性",0],["女性",1]], prompt: "選択してください" %>
  </div>

  <div class="field">
    <%= f.label :"定員" %><br />
    <%= f.number_field :capacity, min: 2, max: 100 %>
  </div>

  <%= f.fields_for :map do |m| %>
    <div class="field">
      <%= m.label :"コース" %><br />
      <%= m.text_field :place, size: 50, autofocus: true, id:"place-search", placeholder:"ゴルフ場名を入力" %>
  <!--     <button id="search">検索</button> -->
    </div>
    <!-- <div id='map'></div> -->
  <% end %>

  <div class="field">
    <%= f.label :"タイトル" %><br />
    <%= f.text_field :round_title, size: 50,autofocus: true, placeholder:"５〜３０文字" %>
  </div>

  <div class="field">
    <%= f.label :"詳細" %><br />
    <%= f.text_area :round_intro, size: "80x10"  %>
  </div>

   <div class="actions">
    <%= f.submit "作成する", class: "btn btn-primary" %>
  </div>
<% end %>

<style>
#map{
  height: 400px;
}
</style>

<script>
function initMap() {
    //対応させるテキストボックス
  // var map = new google.maps.Map(document.getElementById('map'), {
  //   center: {lat: 35.659024, lng: 139.703498},
  //   zoom: 15
  // });
  var input = /** @type {!HTMLInputElement} */(
    document.getElementById('place-search'));
  hoge = new google.maps.places.Autocomplete(input, {
    componentRestrictions: {country: 'jp'},
    types: ['establishment'],
  });
  hoge.addListener('place_changed', function() {
    input.value = this.getPlace().name;
  });

  // var geocoder = new google.maps.Geocoder();
  // document.getElementById('search').addEventListener('click',function(){
  //   geocoder.geocode({
  //     place: docmet.getElementById('place').value
  //   },function(results, status){
  //     if (status !== 'OK'){
  //       alert('Faild:' + status);
  //       return;
  //     }
  //     if(results[0]){
  //       new google.maps.Map(map,{
  //         center: results[0].geometry.location,
  //         zoom: 15
  //       });
  //     }else{
  //       alert('No results found');
  //       return;
  //     }
  //   });
  // });

}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&libraries=places&callback=initMap"
            async defer></script>

app/views/rounds/show.html.erb
<h3 class="heading">ラウンド詳細情報</h3>

<% if user_signed_in? %>
  <% if current_user.id == @master.user_id %>
  <span>
    <%= link_to "ラウンド情報編集", edit_round_path, class:"btn btn-success" %>
  </span>
  <% end %>
<% end %>

<span>
  <%= link_to "ラウンド一覧へ", rounds_path, class:"btn btn-default" %>
  <% if user_signed_in? %>
    <% if @user_round.blank? %>
     <%= link_to "参加申請", apply_round_path(@round.id), method: :post, class:"btn btn-info", "data-confirm" => "このラウンドに参加申請を送りますか？" %>
    <% end %>
  <% end %>
</span>

<table class="table round-info">
  <tr>
    <td><th>タイトル</th></td>
    <td><%= @round.round_title %></td>
  </tr>
  <tr>
    <td><th>主催者</th></td>
    <td><%= link_to @master.user.user_name, user_path(@master.user_id) %></td>
  </tr>
  <tr>
    <td><th>開催日</th></td>
    <td><%= @round.round_date.strftime("20%y年%m月%d日") %></td>
  </tr>
  <tr>
    <td><th>場所</th></td>
    <td><%= @round.prefecture.pref_name %></td>
  </tr>
  <tr>
    <td><th>コース名</th></td>
    <td><%= @round.map.place %></td>
  </tr>
</table>

<% if @lat.present? %>
  <div>
    <div id='map'></div>
  </div>
<% end %>

<div class="count">
  <p class="count-num">
    <%= "参加数：" + @members.count.to_s %>　／　<%= "定員数：" + @round.capacity.to_s %>
  </p>
</div>


<!-- タブ・メニュー -->
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#round-intro" data-toggle="tab">詳細情報</a>
  </li>
  <li>
    <a href="#round-comments" data-toggle="tab">コメント掲示板</a>
  </li>
  <li>
    <a href="#round-members" data-toggle="tab">参加者一覧</a>
  </li>
  <% if user_signed_in? %>
    <% if current_user.id == @master.user_id %>
    <li>
      <a href="#round-applicants" data-toggle="tab">参加希望者</a>
    </li>
    <% end %>
  <% end %>
</ul>

<div class="tab-content">
  <!-- 詳細情報 -->
  <div id="round-intro" class="tab-pane active">
    <%= simple_format(@round.round_intro) %>
  </div>

  <!--　コメント一覧　-->
  <div id="round-comments" class="tab-pane">
    <% if @member.present? %>
      <span>
        <%= form_for @comment, url: comments_path, remote: true do |f| %>
          <%= f.text_area :comment, size: "80x4" %>
          <%= f.submit "投稿", class:"btn btn-primary" %>
        <% end %>
      </span>
    <% end %>
    <table class="table comment-table">
      <% @comments.each do |c| %>
        <div id="comment">
          <%= render partial: 'rounds/comment', locals: {c: c} %>
        </div>
      <% end %>
    </table>
  </div>
  <!--　参加者一覧　-->
  <div id="round-members" class="tab-pane">
    <table class="table">
      <% @members.each.with_index(1) do |member, i| %>
      <div class="member-info">
        <tr>
          <td>
            <strong>
              <%= i.to_s + "．" %>
            </strong>
            <span>
              会員名：<%= link_to member.user.user_name, user_path(member.user_id) %>
            </span>
          </td>
        </tr>
      </div>
      <% end %>
    </table>
  </div>
  <!--　参加希望者一覧　-->
  <div id="round-applicants" class="tab-pane">
    <table class="table">
      <% @apply.each do |apply| %>
        <tr>
          <td>
            <div>
              <span>
                会員名：<%= link_to apply.user.user_name, user_path(apply.user_id) %>
              </span>
              <span>
                <%= apply.created_at.strftime("20%y/%m/%d %H:%M") %>
              </span>
              <% if user_signed_in? %>
                <% if current_user.id == @master.user_id %>
                  <span>
                    <%= link_to "承認", approval_round_path(user_id: apply.user_id, round_id: apply.round_id), method: :patch, class:"btn-sm btn-info", "data-confirm" => "承認しますか？" %>
                  </span>
                  <span>
                    <%= link_to "拒否", refuse_round_path(user_id: apply.user_id, round_id: apply.round_id), method: :delete, class:"btn-sm btn-danger", "data-confirm" => "本当に拒否してもよろしいですか？" %>
                  </span>
                <% end %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

</div>

<!-- googlemap -->
<style>
#map{
  height: 400px;
}
</style>

<script>
  var pos = {lat: <%= @lat %>, lng: <%= @lng %>}
  console.log(pos);

  function initMap(){
    mapInstance = new google.maps.Map(document.getElementById('map'), {
    center: pos,
    zoom: 15
    });

    var marker = new google.maps.Marker({
      map: mapInstance,
      position: pos,
      animation: google.maps.Animation.DROP
    });

  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&language&callback=initMap" async defer></script>