config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'comments/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ####devise###
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }

  ###enduser###
  #homes controller
  root to: 'home#top'
  get '/about', to: 'home#about', as: 'about'
  #users controller
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
  patch '/users/:id', to: 'users#retire', as: 'retire'
  get '/users/retire/complete', to: 'users#complete', as: 'retire_complete'
  #rooms controller
  get '/users/:id/rooms', to: 'rooms#index', as:'myrooms'
  resources :rooms, only: [:create,:show]
  resources :users do
    post '/rooms' => 'rooms#create'
  end

  mount ActionCable.server => '/cable'
  #messages controller
  resources :messages, only: [:create]
  #rounds controller
  get '/myrounds', to: 'rounds#myrounds'
  get '/history', to: 'rounds#history'
  get '/search/rounds', to: 'rounds#search'
  get '/sort/rounds', to: 'rounds#sort'
  post '/round/:id', to: 'rounds#apply', as: 'apply_round'
  patch '/round/:id', to: 'rounds#approval', as: 'approval_round'
  delete '/round/:id', to: 'rounds#refuse', as: 'refuse_round'
  resources :rounds
  get '/maprequest', to: 'rounds#map', as: 'map_request'
  #comments controller
  post '/rounds/:id/comments', to: 'comments#create', as: 'comments'
  get '/rounds/:id/comments/new', to: 'comments#new', as: 'new_comment'
  delete '/comments/:id', to: 'comments#destroy', as: 'comment'

  ###admin###
  namespace :admins do
  	#admins/clients controller
  	resources :clients,  only: [:index]
  	#admins/rounds controller
  	resources :rounds,  only: [:index]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @rounds = Round.last(4)
    @users = User.last(4)
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h3 class="heading">Golf hubとは？</h3>

<p>Golf hubはゴルフ専門のSNSです。</p>

<p>ここでは新たなゴルフ仲間と交流することができます。</p>

<P>たくさんのゴルファーと出会って、より一層ゴルフライフを満喫してください。</P>

app/views/home/top.html.erb
<!-- トップ画像 -->
<div class="top-image">
  <div class="theTarget">
    <div class="image1"></div>
    <div class="image2"></div>
    <div class="image3"></div>
  </div>
</div>

<h3 class="heading">新着ラウンド募集</h3>
<!-- 新着ラウンド募集 -->
<div class="new-rounds">
  <% @rounds.each do |round| %>
  <% if Date.current < round.round_date %>
  <div class="row round-index-box">
    <div class="left-box col-sm-3 col-xs-3">
      <div>
        <!-- 日程 -->
        <%= round.round_date.strftime("20%y年%m月%d日") %>
      </div>
      <div>
        <%= "場　所：" + round.prefecture.pref_name %>
        <!-- 地方id(非表示) -->
        <% round.prefecture.region_id %>
      </div>
      <div>
        <%= "参加数：" + round.users_rounds.where(approval_flag: "1").count.to_s %>
      </div>
      <div>
        <%= "定　員：" + round.capacity.to_s %>
      </div>
    </div>
    <div class="right-box col-sm-9 col-xs-9">
      <div>
        <%= link_to round.round_title, round_path(round) %>
      </div>
      <div>
        <%= "コース名：" + round.map.place %>
      </div>
      <div>
        <%= "主催者　：" + round.users_rounds.first.user.user_name %>
      </div>
      <div>
        <%= "内　容　：" + round.round_intro.truncate(50, omission: '...') %>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
  <div class="round-more">
    <%= link_to "もっと見る", rounds_path %>
  </div>
</div>

<!-- 新着サークル -->
<h3 class="heading">新規サークル情報</h3>
<div style="height:10em">
  <h2>coming soon...</h2>
</div>

<!-- 新会員情報 -->
<h3 class="heading">新規会員情報</h3>
<div class="new-users">
  <% @users.each do |user| %>
  <div class="user-item">

    <% if user_signed_in? %>
    <div>
      <%= link_to user_path(user.id) do %>
        <%= attachment_image_tag user, :user_image, :fill, 120, 120, fallback: "no_image.jpg", size:'120x120' %>
      <% end %>
    </div>
    <div>
      <%= link_to user.user_name, user_path(user.id) %>
    </div>

    <% else %>
    <div>
      <%= link_to new_user_session_path do %>
        <%= attachment_image_tag user, :user_image, :fill, 120, 120, fallback: "no_image.jpg", size:'120x120' %>
      <% end %>
    </div>
    <div>
      <%= link_to user.user_name, new_user_session_path %>
    </div>
    <% end %>

    <div>
      <%= "活動地域：" + user.prefecture.pref_name %>
    </div>
    <div>
      <%= "平均スコア：" + user.av_score %>
    </div>
  </div>
  <% end %>
</div>