config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'comments/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ####devise###
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }

  ###enduser###
  #homes controller
  root to: 'home#top'
  get '/about', to: 'home#about', as: 'about'
  #users controller
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
  patch '/users/:id', to: 'users#retire', as: 'retire'
  get '/users/retire/complete', to: 'users#complete', as: 'retire_complete'
  #rooms controller
  get '/users/:id/rooms', to: 'rooms#index', as:'myrooms'
  resources :rooms, only: [:create,:show]
  resources :users do
    post '/rooms' => 'rooms#create'
  end

  mount ActionCable.server => '/cable'
  #messages controller
  resources :messages, only: [:create]
  #rounds controller
  get '/myrounds', to: 'rounds#myrounds'
  get '/history', to: 'rounds#history'
  get '/search/rounds', to: 'rounds#search'
  get '/sort/rounds', to: 'rounds#sort'
  post '/round/:id', to: 'rounds#apply', as: 'apply_round'
  patch '/round/:id', to: 'rounds#approval', as: 'approval_round'
  delete '/round/:id', to: 'rounds#refuse', as: 'refuse_round'
  resources :rounds
  get '/maprequest', to: 'rounds#map', as: 'map_request'
  #comments controller
  post '/rounds/:id/comments', to: 'comments#create', as: 'comments'
  get '/rounds/:id/comments/new', to: 'comments#new', as: 'new_comment'
  delete '/comments/:id', to: 'comments#destroy', as: 'comment'

  ###admin###
  namespace :admins do
  	#admins/clients controller
  	resources :clients,  only: [:index]
  	#admins/rounds controller
  	resources :rounds,  only: [:index]
  end

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = current_user
    @currentEntries = @user.entries
    myRoomIds = []

    @currentEntries.each do | entry |
      myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?', @user.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

end

app/views/rooms/_message.html.erb
<div class="message">
  <p><%= simple_format(m.content) %></p>
</div>

app/views/rooms/index.html.erb
<h3 class="my-heading">メッセージ一覧</h3>

<% @anotherEntries.each do |e| %>
  <%= link_to e.user.user_name, room_path(e.room.id) %><br />
<% end %>

app/views/rooms/show.html.erb
<h3 class="my-heading">メッセージ</h3>

<div class="left-button">
  <%= link_to "メッセージ一覧", myrooms_path(current_user.id), class:"btn btn-default" %>
</div>
<% @entries.each do |e| %>
  <div class="user-name">
  <% unless current_user.id == e.user.id %>
  <strong>
    <%= image_tag e.user.user_image_id, class:"user-image" %>
      <a class="rooms-user-link" href="/users/<%= e.user.id %>">
        <%= e.user.user_name %>
      </a>
  <% end %>
  </strong>
  </div>
<% end %>
<hr>
<div class="chats">
  <div id="chat" class="chat">
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <div class="chat-box">
          <strong><%= m.user.user_name %></strong>
          <div class="chat-face">
            <!-- attachment_image_tag m.user, :user_image, :fill, 150, 150, format: 'jpeg', fallback: "no_image.jpg", size:'150x150' %> -->
          </div>
          <div class="chat-hukidashi"><%= render 'message',m: m %><br>
            <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="posts">
    <%= form_for @message do |f| %>
      <%= f.text_field :content, placeholder: "メッセージを入力して下さい" , size: 70, id: "message", class: "form-text-field" %>
        <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit "投稿", class: 'form-submit'%>
    <% end %>
  </div>
</div>

<script>
  $(function(){
    $(".chat").scrollTop($("#chat")[0].scrollHeight);
  });
</script>